# Generated by Django 4.2.3 on 2023-08-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='username',
            new_name='felhasznalonev',
        ),
    ]
