# Generated by Django 4.2.3 on 2023-08-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_is_staff_account_feltolto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_admin',
            new_name='admin',
        ),
    ]
