# Generated by Django 4.2.3 on 2023-08-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_is_admin_account_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
    ]
