# Generated by Django 4.2.3 on 2023-07-24 17:28

from django.db import migrations, models
import video.models



class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_remove_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_from_url',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(default='', upload_to=video.models.upload_location),
        ),
    ]
