# Generated by Django 4.2.3 on 2023-07-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_alter_post_video_alter_post_video_from_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_from_url',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
    ]
