# Generated by Django 4.2.3 on 2023-08-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_alter_post_video_from_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tancos',
            new_name='adatkozlo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='boritokep',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='datum',
            new_name='fdatum',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='hely',
            new_name='talyegyseg',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='tancnev',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_from_url',
        ),
    ]
